Repository Saher-Amasha/to-do-list, pull requests merged in 2022-01, with the labels that each got.

#3 Edit the ReadMe file
  README.md
Labels: documentation

#4 initialized project.
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/to_do_list_fv/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/to_do_list_fv/MainActivity.java
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/example/to_do_list_fv/ExampleUnitTest.java
  build.gradle
  git
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: enhancement

#5 added and configured firebase database and created class TaskHelper
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/google-services.json
  app/src/main/java/com/example/to_do_list_fv/MainActivity.java
  app/src/main/java/com/example/to_do_list_fv/TaskHelper.java
  build.gradle
Labels: enhancement

#7 modified file gitignore
  .idea/.gitignore
Labels: enhancement

#8 second modifcation to gitignore file
  .gitignore
  .idea/.gitignore
Labels: enhancement

#11 Design home page & Add app bar
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/to_do_list_fv/MainActivity.java
  app/src/main/res/drawable/add.xml
  app/src/main/res/drawable/ic_baseline_done_24.xml
  app/src/main/res/drawable/ic_search_black_24dp.xml
  app/src/main/res/drawable/to_do_list.png
  app/src/main/res/font/neonderthaw_regular.ttf
  app/src/main/res/font/opensans_extrabold.ttf
  app/src/main/res/font/quicksand_bold.ttf
  app/src/main/res/font/quicksand_light.ttf
  app/src/main/res/font/quicksand_medium.ttf
  app/src/main/res/font/quicksand_regular.ttf
  app/src/main/res/font/quicksand_semibold.ttf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/all_tasks.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/ic_plus_24.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: documentation, enhancement

#12 added login and signup activity and linked them
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/to_do_list_fv/LoginActivity.java
  app/src/main/java/com/example/to_do_list_fv/SignupActivity.java
  app/src/main/res/drawable/email_icon.xml
  app/src/main/res/drawable/user_icon.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
